### ISSUE TITLE
Cant use any of the inputs when streaming

### ISSUE THREAD

**Issue by Yorisoft** [XK9274/screencap-toolkit-miyoo#1]
Thanks for the great App!

Im unable to use any of the inputs when streaming to Twitch or using VNC. Device seems to freez up. 

Mind providing more guidance on how to get it working

**Comment by XK9274** [comment]
Hey. 

I'll be removing these repos soon tbh. VNC and screen recorder will be in onion 4.3, they were more of a discovery thing to see how well the miyoo coped with encoding. 

Just fyi there's no audio on the streams, with that said if you want to fix them you can try removing/commenting out the lines in the launch.sh files within the relevant app as these are what cause the lockups. 

You'll see a line for when it's started and a line for when it's stopped, comment out both. You'll get no feedback that it's started when you do this.

**Comment by Yorisoft** [comment]
Thanks for the info! Hopefully it works more consistently when officially added to onion. 

I've tried to un-commented the lines, and finally got the input to work.  Im still not able to rotate the screen tho. Might 


```
#!/bin/sh
cd /mnt/SDCARD/App/VNCserver/
export sysdir=/mnt/SDCARD/.tmp_update
export miyoodir=/mnt/SDCARD/miyoo
export LD_LIBRARY_PATH="/mnt/SDCARD/App/VNCserver/lib:/lib:/config/lib:$miyoodir/lib:$sysdir/lib:$sysdir/lib/parasyte"
export PATH="$sysdir/bin:$PATH"

IP=$(ip route get 1 | awk '{print $NF;exit}')

if pgrep vncserver > /dev/null; then
    killall -9 vncserver
	/mnt/SDCARD/.tmp_update/bin/infoPanel -t "VNC Server Shutdown" -m "VNC Server Shutdown" --auto &
else
    /mnt/SDCARD/App/VNCserver/bin/vncserver -k /dev/input/event0 -F 20 &
	/mnt/SDCARD/.tmp_update/bin/infoPanel -t "Launching VNC Server" -m "VNC Server has been launched: \n $IP:5900" --auto &
fi

  ./vncserver -k /dev/input/event0 -r 90 -F 20
 -p port: VNC port, default is 5900
 -f device: framebuffer device node, default is /dev/fb0
 -k device: keyboard device node (example: /dev/input/event0)
 -t device: touchscreen device node (example:/dev/input/event2)
 -r degrees: framebuffer rotation, default is 0
 -R degrees: touchscreen rotation, default is same as framebuffer rotation
 -F FPS: Maximum target FPS, default is 10
 -v: verbose
 -h: print this help

# Keyboard support works but only for SDLK inputs programmed into whatever you're using (so arrow keys work, space is enter) 
# I suspect if SDL keys were programmed for the keyboard inputs for each key (such as in simple terminal) you'd be able to use these inputs too. 


```

**Comment by XK9274** [comment]
No worries! That version of VNC doesn't support 32bpp. The one in onion does and there's a repo on my GitHub for the source of you have the ability to build it. 

Onion won't have twitch streaming though, I don't think it's in the best place to include it.

**Comment by Yorisoft** [comment]
@XK9274 
The screen rotation isn't working. Might you know how I can fix it?

**Comment by XK9274** [comment]
As mentioned the version of VNC in this repo does not support rotation at 32bpp. You have to use a VNC viewer that can rotate. 

The version in Onion 4.3 will.

**Comment by Yorisoft** [comment]
Ah now I understand. Thank you for clarifying mate! 

Let me see if I can figure out how to build that version for the miyoo. 
Might you be willing to update this repo with that version? In case I don't succeed in building it. 

Also when is 4.3 coming out??

I'm all set btw, Feel free to close this one out.

**Comment by XK9274** [comment]
Of course. I'm at work at the minute. Should have time tonight - will update the issue when it's uploaded.

**Comment by XK9274** [comment]
https://github.com/XK9274/screencap-toolkit-miyoo/commit/22a46604e8bee58c5644690bc1a40f3a51d78a84

Can you give this a test, there is a new binary and a slight change to launch.sh - let me know if there's other issues, if not feel free to close & Merry Christmas!

4.3 is coming very soon :)
